import { parseClientEnvironment } from "./env.client.schema";

export const clientEnvironment = parseClientEnvironment({
  NEXT_PUBLIC_APP_ENV: process.env.NEXT_PUBLIC_APP_ENV,
  NEXT_PUBLIC_GIWA_CHAIN_ID: process.env.NEXT_PUBLIC_GIWA_CHAIN_ID,
  NEXT_PUBLIC_GIWA_EXPLORER_URL: process.env.NEXT_PUBLIC_GIWA_EXPLORER_URL,
  NEXT_PUBLIC_GIWA_RPC_URL: process.env.NEXT_PUBLIC_GIWA_RPC_URL,
  NEXT_PUBLIC_PARTICIPATION_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_PARTICIPATION_CONTRACT_ADDRESS,
  NEXT_PUBLIC_PINATA_GATEWAY_URL: process.env.NEXT_PUBLIC_PINATA_GATEWAY_URL,
  NEXT_PUBLIC_PRIVY_APP_ID: process.env.NEXT_PUBLIC_PRIVY_APP_ID,
});
